-d C:\odev\sicaklikk\impl\gwsynthesis\sicaklikk.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst C:\odev\sicaklikk\src\sicaklikk.cst
-cfg C:\odev\sicaklikk\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 10
